### ISSUE TITLE
Accepting Azure MP listings is not idempotent, use a null resource with python3 or achieve the same with requests

### ISSUE THREAD

**Issue by trvsmtchll** [terraform-aviatrix-modules/terraform-aviatrix-azure-controlplane#1]
If someone is or is not subscribed to the controller & copilot azure listings the code should not fail or require the user to do any further manual modifications. This can be achieved by using a null resource & python like so.

`resource "null_resource" "accept_license" {
   provisioner "local-exec" {
       command = "python3 ./accept_license.py"
   }
}`

The contents of accept_license.py follow containing using current offer:plan:version details.

`import subprocess
import json

process = subprocess.Popen(['az','vm', 'image', 'terms', 'show', '--urn', 'aviatrix-systems:aviatrix-bundle-payg:aviatrix-enterprise-bundle-byol:latest'], stdout=subprocess.PIPE)
out, err = process.communicate()
d = json.loads(out)
if d['accepted'] == False:
    process = subprocess.Popen(['az','vm', 'image', 'terms', 'accept', '--urn', 'aviatrix-systems:aviatrix-bundle-payg:aviatrix-enterprise-bundle-byol:latest'], stdout=subprocess.PIPE)`

We need this change incorporated to allow for straight through processing whether someone is subscribed to one of the vm listings or not.

**Comment by Dennizz** [comment]
Addressed in special branch for this use case.
